#!/system/bin/sh

VERSION=1.0

DISPLAY_VERSION() {
	echo "/sbin/ptp by jcadduono (version $VERSION)"
}

DISPLAY_USAGE() {
	echo "Usage: ptp [on|off|status]"
	echo "Enables or disables Picture Transfer Protocol USB mode."
	echo
	echo "  on, start, enable    turns on PTP mode"
	echo "  off, stop, disable   turns off PTP mode"
	echo "  -i, info, status     displays status of USB mode"
	echo "  -h, help             displays this information"
	echo "  -v, version          displays version info"
	echo
	echo "For more help & to report bugs contact <jc@adduono.com>"
}

case $1 in
1|on|start|enable)
	/sbin/usb ptp on
	;;
0|off|stop|disable)
	/sbin/usb ptp off
	;;
-i|info|status)
	/sbin/usb status
	;;
-v|version)
	DISPLAY_VERSION
	;;
*)
	DISPLAY_USAGE
	;;
esac
