#!/system/bin/sh

VERSION=1.2

LUN=/sys/devices/msm_dwc3/f9200000.dwc3/gadget/lun0
SDCARD=/dev/block/mmcblk1
SDMOUNT=/storage/extSdCard
SD_MOUNTED=false
USB_MODE=false
ADB_ON=false
UMS_WAS_ON=false

DISPLAY_VERSION() {
	echo "/sbin/usb by jcadduono (version $VERSION)"
}

DISPLAY_USAGE() {
	echo "Usage: usb [mtp|ptp|ums|status] [on|off]"
	echo "Enables or disables MTP, PTP, and UMS USB modes."
	echo
	echo "  mtp on/off           turns on/off MTP mode"
	echo "  ptp on/off           turns on/off PTP mode"
	echo "  ums on/off           turns on/off UMS mode"
	echo "  default              sets USB mode to default"
	echo "  -i, info, status     displays active USB mode"
	echo "  -h, help             displays this information"
	echo "  -v, version          displays version info"
	echo
	echo "For more help & to report bugs contact <jc@adduono.com>"
}

CHECK_SU() {
	[ -z "$(ls /data/data)" ] && {
		echo "Must be superuser!" 1>&2
		exit 1
	}
}

CHECK_SD_MOUNTED() {
	mountpoint -q $SDMOUNT && SD_MOUNTED=true || SD_MOUNTED=false
}

CHECK_ADB_ON() {
	case "$(getprop sys.usb.state)" in
	*adb*)
		ADB_ON=true
		;;
	*)
		ADB_ON=false
		;;
	esac
}

CHECK_USB_MODE() {
	case "$(getprop sys.usb.state)" in
	*mtp*)
		USB_MODE="mtp"
		;;
	*ptp*)
		USB_MODE="ptp"
		;;
	*mass_storage*)
		USB_MODE="ums"
		;;
	*)
		USB_MODE=false
		;;
	esac
}

DISPLAY_STATUS() {
	CHECK_USB_MODE
	case "$USB_MODE" in
	mtp)
		echo "Media Transfer Protocol is active."
		;;
	ptp)
		echo "Picture Transfer Protocol is active."
		;;
	ums)
		echo "USB Mass Storage is active."
		;;
	*)
		echo "No USB transfer modes are active."
		;;
	esac
	CHECK_SD_MOUNTED
	$SD_MOUNTED && {
		echo "SDcard is currently mounted in Android."
	} || {
		echo "SDcard is not mounted in Android."
	}
}

ACTIVATE_USB_MODE() {
	WAIT_COUNT=0
	setprop sys.usb.config $USB_MODE
	while [ "$(getprop sys.usb.state)" != "$USB_MODE" ]
	do
		echo -n "."
		sleep 0.1
		WAIT_COUNT=$(($WAIT_COUNT+1))
		[ $WAIT_COUNT -eq 10 ] && {
			echo
			echo "Error: USB mode does not want to change!" 1>&2
			exit 1
		}
	done
	echo
}

ASK_RETRY() {
	echo -n "Retry? (y/n): "
	read RETRY
	case "$RETRY" in
	y|Y|1|yes)
		return
		;;
	esac
	exit 1
}

MOUNT_SDCARD() {
	CHECK_SD_MOUNTED
	$SD_MOUNTED && return
	echo "Mounting SDcard to $SDMOUNT..."
	vdc volume mount $SDMOUNT > /dev/null 2>&1
	CHECK_SD_MOUNTED
	$SD_MOUNTED && {
		echo "SDcard mounted successfully."
		sleep 1
	} || {
		echo "Error: Unable to mount SDcard!" 1>&2
		ASK_RETRY
		MOUNT_SDCARD
	}
}

UNMOUNT_SDCARD() {
	CHECK_SD_MOUNTED
	$SD_MOUNTED || return
	echo "Unmounting SDcard from $SDMOUNT..."
	vdc volume unmount $SDMOUNT > /dev/null 2>&1
	CHECK_SD_MOUNTED
	$SD_MOUNTED && {
		echo "Error: Unable to unmount SDcard!" 1>&2
		ASK_RETRY
		UNMOUNT_SDCARD
	} || {
		echo "SDcard unmounted successfully."
	}
}

ASK_MOUNT_SDCARD() {
	CHECK_SD_MOUNTED
	$SD_MOUNTED && return
	echo -n "Mount SDcard in Android? (y/n): "
	read OPEN
	case "$OPEN" in
	y|Y|1|yes)
		MOUNT_SDCARD
		;;
	esac
}

MTP_ON() {
	USB_OFF
	CHECK_ADB_ON
	$ADB_ON && MODE="mtp,adb" || MODE="mtp"
	echo -n "Activating MTP USB transfer mode..."
	USB_MODE=$MODE
	ACTIVATE_USB_MODE
}

PTP_ON() {
	USB_OFF
	CHECK_ADB_ON
	$ADB_ON && MODE="ptp,adb" || MODE="ptp"
	echo -n "Activating PTP USB transfer mode..."
	USB_MODE=$MODE
	ACTIVATE_USB_MODE
}

UMS_ON() {
	USB_OFF
	UNMOUNT_SDCARD
	echo "Setting up dwc3 storage gadget lun..."
	echo 0 > $LUN/cdrom
	echo 0 > $LUN/nofua
	echo 0 > $LUN/ro
	echo "Mounting $SDCARD to lun..."
	echo $SDCARD > $LUN/file
	CHECK_ADB_ON
	$ADB_ON && MODE="mass_storage,adb" || MODE="mass_storage"
	echo -n "Activating USB Mass Storage transfer mode..."
	USB_MODE=$MODE
	ACTIVATE_USB_MODE
}

UMS_OFF() {
	echo "Disabling dwc3 storage gadget lun..."
	echo 0 > $LUN/cdrom
	echo 0 > $LUN/nofua
	echo 0 > $LUN/ro
	echo 0 > $LUN/file
	UMS_WAS_ON=true
}

USB_OFF() {
	CHECK_USB_MODE
	[ $USB_MODE == "ums" ] && UMS_OFF
	CHECK_ADB_ON
	$ADB_ON && MODE="adb" || MODE="none"
	echo -n "Disabling USB transfer protocols..."
	USB_MODE=$MODE
	ACTIVATE_USB_MODE
	$UMS_WAS_ON && ASK_MOUNT_SDCARD
}

USB_DEFAULT() {
	USB_OFF
	echo -n "Setting USB mode to default..."
	USB_MODE="$(getprop persist.sys.usb.config)"
	ACTIVATE_USB_MODE
}

case $1 in
mtp)
	CHECK_SU
	case $2 in
	1|on|start|enable)
		MTP_ON
		echo "Done."
		;;
	0|off|stop|disable)
		USB_OFF
		echo "Done."
		;;
	*)
		DISPLAY_USAGE
		;;
	esac
	;;
ptp)
	CHECK_SU
	case $2 in
	1|on|start|enable)
		PTP_ON
		echo "Done."
		;;
	0|off|stop|disable)
		USB_OFF
		echo "Done."
		;;
	*)
		DISPLAY_USAGE
		;;
	esac
	;;
ums)
	CHECK_SU
	case $2 in
	1|on|start|enable)
		UMS_ON
		echo "Done. PLEASE USE EJECT MEDIA ON PC BEFORE TURNING OFF UMS!"
		;;
	0|off|stop|disable)
		USB_OFF
		echo "Done."
		;;
	*)
		DISPLAY_USAGE
		;;
	esac
	;;
default)
	CHECK_SU
	USB_DEFAULT
	echo "Done."
	;;
-i|info|status)
	DISPLAY_STATUS
	;;
-v|version)
	DISPLAY_VERSION
	;;
*)
	DISPLAY_USAGE
	;;
esac
