#!/system/bin/sh

detectsu=`ls /data/data`
[ -z "$detectsu" ] && echo "Must be superuser!" && exit

while true; do

echo
echo "leanKernel configurator"
echo "---"
echo "0) display current settings"
echo "1) panel temperature"
echo "2) panel color"
echo "3) set screen_off_maxfreq"
echo "4) set cpu max frequency"
echo "5) gpu governor"
echo
echo "9) check top 10 wake locks (ie. wakeup sources)"
echo
echo -n "please enter a number (or press enter to exit): "

read option

case $option in
0)
	echo
	echo "current settings"
	echo "----------------"
	echo -n "1) panel temperature: "
	cat /sys/class/lcd/panel/temperature
	echo -n "2) panel color: "
	cat /sys/class/lcd/panel/panel_colors
	echo -n "3) screen off maxfreq: "
	cat `ls -d /sys/devices/system/cpu/cpufreq/*a*`/screen_off_maxfreq
	echo -n "4) cpu max frequency: "
	cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
	echo -n "5) gpu governor: "
	cat /sys/devices/fdb00000.qcom,kgsl-3d0/devfreq/fdb00000.qcom,kgsl-3d0/governor
	echo
	;;
1) 
	echo -n "Enter a number between -60 and 0 (0 is kernel default): "
	read value
	echo $value > /data/data/leankernel/paneltemp
	echo $value > /sys/class/lcd/panel/temperature
	echo "Done! (also will persist at boot)"
	;;
2)	
	echo -n "Enter a number between 0 and 4 (2 is kernel default): "
	read value
	echo $value > /data/data/leankernel/panelcolor
	echo $value > /sys/class/lcd/panel/panel_colors
	echo "Turn off screen and back on (also will persist at boot)"
	;;
3)	
	echo -n "Enter a number between 0 and 4 (0:650mhz,1:883mhz,2:1.2ghz/default,3:1.5ghz,4:disable): "
	read value
	case $value in
	  0) FREQ=652800;;
	  1) FREQ=883200;;
	  2) FREQ=1267200;;
	  3) FREQ=1574400;;
	  4) FREQ=2265600;;
	esac
	echo $FREQ > /data/data/leankernel/screen_off_maxfreq
	echo $FREQ > `ls -d /sys/devices/system/cpu/cpufreq/*a*`/screen_off_maxfreq
	echo "Done! (also will persist at boot)"
	;;
4)
	echo -n "Enter a number between 0 and 2 (0:2.2ghz,1:2.5ghz,2:2.7ghz): "
	read value
	case $value in
	  0) FREQ=2265600;;
	  1) FREQ=2496000;;
	  2) FREQ=2726400;;
	esac
	echo $FREQ > /data/data/leankernel/scaling_max_freq
	echo $FREQ > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
	echo "Done! (also will persist at boot)"
	;;
5)
        echo -n "Enter a number between 0 and 3 (0:adreno-tz/default,1:powersave,2:performance,3:ondemand): "
        read value
        case $value in
          0) GOV=msm-adreno-tz;;
          1) GOV=powersave;;
          2) GOV=performance;;
          3) GOV=simple_ondemand;;
        esac
	echo $GOV > /data/data/leankernel/gpu_governor
	echo $GOV > /sys/devices/fdb00000.qcom,kgsl-3d0/devfreq/fdb00000.qcom,kgsl-3d0/governor
	echo "Done! (also will persist at boot)"
	;;
9)
        echo
        if [ -a /system/xbin/awk ]; then
                echo "1st column: total time wakeup source has been active."
                echo "2nd column: max time the source was continuously active."
                echo "(The numbers are duration in seconds)"
                echo "-----"
                cat /sys/kernel/debug/wakeup_sources | grep -v wakeup_count \
                  | awk '{ printf "%-10s%-8s %s\n",int($7/1000),int($8/1000),$1 }' \
                  | sort -rn | head -10
        else
                echo "busybox required!"
        fi
        ;;
*)
	exit
	;;
esac
echo
done
